---
- name: Setup Server with Docker on AWS EC2 Instance
  hosts: all
  become: yes
  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install Docker and Git
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - docker.io
        - git

    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Verify Docker installation
      command: docker --version
      register: docker_version
      failed_when: false

    - name: Display Docker version
      debug:
        msg: "Docker version is: {{ docker_version.stdout }}"
